name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tag
      run: |
       echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
       
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag ghcr.io/pretsbarnabas/azuretest:$IMAGE_TAG --tag ghcr.io/pretsbarnabas/azuretest:latest
       docker login ghcr.io -u pretsbarnabas -p ${{secrets.GHCR_TOKEN}}
       docker push ghcr.io/pretsbarnabas/azuretest:$IMAGE_TAG
       docker push ghcr.io/pretsbarnabas/azuretest:latest
       
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TestPB'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0423cdfc778425c95922147f94486dd }}
        images: 'ghcr.io/pretsbarnabas/azuretest:${{env.IMAGE_TAG}}'
